server:
  port: 8083
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 139.224.233.37:8848
        heart-beat-interval: 5000
        heart-beat-timeout: 20000
        namespace: prod
        register-enabled: true
        username: nacos
        password: nacos